name: Nanci Zurek
favicon: null
layout_spectrum: 0.23654111754149199
typography_spectrum: 0.07123946654610336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6156989233568311
  lightness: 0.5623071321751922
  saturation: 0.10945145902223885
  rhythmicContrast: 0.16028063418343663
purpose: []
